// <auto-generated />
using System;
using Komunalka.DAL.KomunalDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Komunalka.DAL.Migrations
{
    [DbContext(typeof(KomunalContext))]
    [Migration("20200831171134_Simplify")]
    partial class Simplify
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Komunalka.DAL.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Komunalka.DAL.Models.PayingComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CounterIndicationsCurrent")
                        .HasColumnType("int");

                    b.Property<int>("CounterIndicationsDifference")
                        .HasColumnType("int");

                    b.Property<int>("CurrentIndicationsPrevious")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountIndicationsAmount")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<double>("RateCommon")
                        .HasColumnType("float");

                    b.Property<double?>("RateDiscount")
                        .HasColumnType("float");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Summa")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("PayingComponent");
                });

            modelBuilder.Entity("Komunalka.DAL.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Komunalka.DAL.Models.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceProvider");
                });

            modelBuilder.Entity("Komunalka.DAL.Models.PayingComponent", b =>
                {
                    b.HasOne("Komunalka.DAL.Models.Payment", "Payment")
                        .WithMany("PayingComponent")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK__PayingCom__Payme__5CD6CB2B")
                        .IsRequired();

                    b.HasOne("Komunalka.DAL.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("PayingComponent")
                        .HasForeignKey("ServiceProviderId")
                        .HasConstraintName("FK__PayingCom__Servi__5DCAEF64")
                        .IsRequired();
                });

            modelBuilder.Entity("Komunalka.DAL.Models.Payment", b =>
                {
                    b.HasOne("Komunalka.DAL.Models.Customer", "Customer")
                        .WithMany("Payment")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Payment__Custome__37A5467C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
